### ISSUE TITLE
add ocaml discourse site

### ISSUE THREAD

**Issue by pmetzger** [rizo/awesome-ocaml#125]
https://discuss.ocaml.org/ ought to be listed under "community" I think.

**Comment by gasche** [comment]
That's an excellent point, would you like to submit a Pull Request?

**Comment by pmetzger** [comment]
The fastest way to do that is to fork the repo, make the change, request a pull?

**Comment by gasche** [comment]
If you go on the [README.md](https://github.com/rizo/awesome-ocaml/blob/master/README.md) file in the repo, it has an "edit this file" button that you can use to edit online.

**Comment by pmetzger** [comment]
Done, and pullup requested.

**Comment by rizo** [comment]
Closing this, the discourse website is already in the list.
