### ISSUE TITLE
PEG Parser

### ISSUE THREAD

**Issue by mbouaziz** [rizo/awesome-ocaml#44]
The OPA language repository contains a powerful parser for PEG grammars:

https://github.com/MLstate/opalang/tree/master/tools/teerex

**Comment by rizo** [comment]
Do you know if the parser is available as an independent library?

This repository is mainly for _resources_, something that can be referenced and directly used. Although it's certainly useful, I'm not sure if it's Ok to just place a link to a source tree with a parser.

Interestingly, I've found already several times beautiful examples of OCaml code, used in real world projects, but don't know if I should place them here. Maybe we could create a separate section for code example?

@MassD @Engil @Drup @V01D-eXe 
Guys, what do you think?

**Comment by rizo** [comment]
Also, OPA language is already listed, so someone curious about the parser implementation may just go and see the source code.

**Comment by V01D-eXe** [comment]
If it can be compiled and used independently of Opa, it should be good to go. 
BTW it was last updated on 2012, so ..........
