### ISSUE TITLE
[Proposal] Add typeocaml to list

### ISSUE THREAD

**Issue by teekaay** [rizo/awesome-ocaml#48]
## Introduction
The website [typeocaml](http://typeocaml.com/) has several tutorials on algorithms and data structures. 
It seems up to date and has a very nice design. I cannot say much about the learning experience since I am not an active OCaml developer (visited the website a few times out of interest) but it is well written and structured in a very concise way.
**Website**: http://typeocaml.com/
## Suggestion
Add it to **Blogs** or create a **Tutorials** as a new point on the list.

**EDIT**: It seems that I have not realized "Many things about OCaml". Can be closed, sorry.

**Comment by rizo** [comment]
Hey, nevertheless thanks for the suggestion, perhaps the link should include "Type OCaml" in the title, will fix.
