### ISSUE TITLE
TUI

### ISSUE THREAD

**Issue by Freyr666** [rizo/awesome-ocaml#93]
There is ``Graphics'' section, but what about text user interfaces? For example there is an awesome TUI library, lambda-term (https://github.com/diml/lambda-term), but i can't figure out to what section it belongs.

**Comment by gasche** [comment]
I would split "Graphics" into "Graphics" and "User Interface", where the latter would have both the current content of the "GUI" subsection and lambda-term. (We could later sub-split it into "Graphic" vs "Textual" UIs, but I don't see a need for now.)

**Comment by rizo** [comment]
@Freyr666 Thanks!

@gasche A followed your suggestion and split the Graphics section. See 55a413fc2f5091cabc487c5eb2fd453f850c7be0
