### ISSUE TITLE
Add vscode-ocaml as a suggestion for Editor Plugins

### ISSUE THREAD

**Issue by raztd** [rizo/awesome-ocaml#99]
VSCode + OCaml plugin + merlin is an easy way for beginners to start coding in OCaml.

https://github.com/hackwaly/vscode-ocaml

![vscode](https://cloud.githubusercontent.com/assets/6805609/24148283/cbfa1b72-0e46-11e7-85b3-4d8886ee6328.png)

**Comment by gasche** [comment]
That sounds reasonable. Would you be willing to submit a pull request to that effect?

**Comment by raztd** [comment]
done
